import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Tv, Key, AlertTriangle } from "lucide-react";
import { toast } from "sonner";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [requireCode, setRequireCode] = useState(false);
  const [codeUnavailable, setCodeUnavailable] = useState(false);
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { session, role, loading: authLoading } = useAuth();

  // Auto-redirect if already logged in
  useEffect(() => {
    if (!authLoading && session) {
      navigate(role === "admin" ? "/admin" : "/", { replace: true });
    }
  }, [session, authLoading, role, navigate]);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    if (requireCode) {
      if (!code.trim() || code.length !== 4) {
        toast.error("Enter the 4-digit verification code.");
        setLoading(false);
        return;
      }
      const { data, error } = await (supabase.auth as any).verifyCode({ email, password, code });
      setLoading(false);
      if (error) {
        toast.error(error.message || "Verification failed");
      }
      return;
    }

    const res = await supabase.auth.signInWithPassword({ email, password });
    setLoading(false);
    
    if (res?.error) {
      const errorMsg = res.error.message;
      if (errorMsg.includes("verification code must be generated") || errorMsg.includes("code_required")) {
        setCodeUnavailable(true);
      } else {
        toast.error(errorMsg);
      }
    } else if (res?.data && (res.data as any).require_code) {
      setRequireCode(true);
      toast.success("Verification required", {
        description: "Please enter the 4-digit verification code generated by your Super Admin.",
      });
    }
  };

  if (authLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full" />
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-background p-4">
      <Card className="w-full max-w-sm">
        <CardHeader className="text-center space-y-2">
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-primary">
            <Tv className="h-6 w-6 text-primary-foreground" />
          </div>
          <CardTitle className="text-xl">SignageHub</CardTitle>
          <CardDescription>
            {codeUnavailable
              ? "Verification Required"
              : requireCode
              ? "Enter Authorization Code"
              : "Sign in to your account"}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {codeUnavailable ? (
            <div className="space-y-4">
              <div className="rounded-lg border border-amber-500/20 bg-amber-500/10 p-3 text-sm text-amber-500 flex gap-2">
                <AlertTriangle className="h-5 w-5 shrink-0" />
                <div className="space-y-1">
                  <p className="font-semibold">Code Generation Required</p>
                  <p className="text-xs opacity-90">
                    A local login requires a verification code. Please ask a Super Admin to
                    generate a login code for your account from the cloud console.
                  </p>
                </div>
              </div>
              <Button
                type="button"
                variant="outline"
                className="w-full"
                onClick={() => setCodeUnavailable(false)}
              >
                Back to Sign In
              </Button>
            </div>
          ) : (
            <form onSubmit={handleLogin} className="space-y-4">
              {!requireCode ? (
                <>
                  <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input
                      id="email"
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      placeholder="admin@example.com"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="password">Password</Label>
                    <Input
                      id="password"
                      type="password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      placeholder="••••••••"
                      required
                    />
                  </div>
                </>
              ) : (
                <div className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="code">Verification Code</Label>
                    <Input
                      id="code"
                      type="text"
                      maxLength={4}
                      placeholder="_ _ _ _"
                      value={code}
                      onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
                      className="text-center text-xl font-semibold tracking-widest font-mono h-11"
                      required
                      autoFocus
                    />
                    <p className="text-[11px] text-muted-foreground text-center">
                      Enter the 4-digit code generated by the Super Admin.
                    </p>
                  </div>
                  <button
                    type="button"
                    className="text-xs text-muted-foreground underline block mx-auto hover:text-foreground cursor-pointer"
                    onClick={() => {
                      setRequireCode(false);
                      setCode("");
                    }}
                  >
                    ← Back to Sign In
                  </button>
                </div>
              )}
              <Button type="submit" className="w-full" disabled={loading}>
                {loading
                  ? requireCode
                    ? "Verifying..."
                    : "Signing in..."
                  : requireCode
                  ? "Verify Code"
                  : "Sign In"}
              </Button>
            </form>
          )}

          <div className="mt-6 pt-4 border-t">
            <p className="text-[11px] uppercase tracking-widest text-red-600 text-center">
              Connected to Plesk backend
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
